# Generated by Django 4.2 on 2023-04-19 18:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0004_remove_user_profil_name_user_profil_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cours',
            old_name='heure',
            new_name='heuredebut',
        ),
        migrations.RenameField(
            model_name='rendezvous',
            old_name='heure',
            new_name='heuredebut',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='date',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='date',
        ),
        migrations.RemoveField(
            model_name='user_profil',
            name='role',
        ),
        migrations.AddField(
            model_name='cours',
            name='heurefin',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='heurefin',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='paye',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eleve', to='gestion_cours.user_profil'),
        ),
        migrations.AlterField(
            model_name='inspecteur',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspecteur', to='gestion_cours.user_profil'),
        ),
        migrations.AlterField(
            model_name='secretaire',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secretaire', to='gestion_cours.user_profil'),
        ),
    ]
