# Generated by Django 4.2 on 2023-04-27 09:02

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0005_rename_heure_cours_heuredebut_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user_profil',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
