# Generated by Django 4.2 on 2023-04-27 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0006_alter_user_profil_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
