# Generated by Django 4.2 on 2023-04-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0007_cours_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='heuredebut',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cours',
            name='heurefin',
            field=models.DateTimeField(),
        ),
    ]
