# Generated by Django 4.2 on 2023-04-27 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0008_alter_cours_heuredebut_alter_cours_heurefin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='date',
        ),
    ]
