# Generated by Django 4.2 on 2023-04-27 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0010_heure'),
    ]

    operations = [
        migrations.AddField(
            model_name='heure',
            name='heureRestant',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
