# Generated by Django 4.2 on 2023-04-27 19:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0011_heure_heurerestant'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='inspecteur',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='eleve', to='gestion_cours.inspecteur'),
            preserve_default=False,
        ),
    ]
