# Generated by Django 4.2 on 2023-04-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gestion_cours', '0012_eleve_inspecteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profil',
            name='Eleve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_profil',
            name='Inspecteur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_profil',
            name='Secretaire',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_profil',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='auth_group', related_query_name='auth_group', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user_profil',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='auth_group', related_query_name='auth_group', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
