# Generated by Django 4.2 on 2023-04-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0013_user_profil_eleve_user_profil_inspecteur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profil',
            name='Eleve',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user_profil',
            name='Inspecteur',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user_profil',
            name='Secretaire',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
