# Generated by Django 4.2 on 2023-04-29 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0014_alter_user_profil_eleve_alter_user_profil_inspecteur_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profil',
            old_name='Eleve',
            new_name='Eleves',
        ),
        migrations.RenameField(
            model_name='user_profil',
            old_name='Inspecteur',
            new_name='Inspecteurs',
        ),
        migrations.RenameField(
            model_name='user_profil',
            old_name='Secretaire',
            new_name='Secretaires',
        ),
    ]
