# Generated by Django 4.2 on 2023-04-29 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0015_rename_eleve_user_profil_eleves_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user_profil',
            managers=[
            ],
        ),
    ]
