# Generated by Django 4.2 on 2023-04-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0016_alter_user_profil_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heure',
            name='heureRestant',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
