# Generated by Django 4.2 on 2023-04-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0017_alter_heure_heurerestant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='paye',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='paye',
        ),
        migrations.AddField(
            model_name='cours',
            name='lieu',
            field=models.CharField(default='25 rue de la paix 75000 Paris', max_length=100),
        ),
        migrations.AddField(
            model_name='cours',
            name='title',
            field=models.CharField(default='Cours de conduite', max_length=100),
        ),
    ]
