# Generated by Django 4.2 on 2023-05-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0018_remove_cours_paye_remove_rendezvous_paye_cours_lieu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='heureDispo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eleve',
            name='heureindispo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
