# Generated by Django 4.2 on 2023-05-02 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cours', '0019_eleve_heuredispo_eleve_heureindispo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eleve',
            old_name='heureDispo',
            new_name='heuredispo',
        ),
    ]
